version: '3.8'

services:
  sb-proxy:
    build: .
    container_name: sb-proxy
    network_mode: host
    restart: unless-stopped
    environment:
      - PORT=30000
      - CONFIG_DIR=/app/config
      - TURSO_DATABASE_URL=${TURSO_DATABASE_URL}
      - TURSO_AUTH_TOKEN=${TURSO_AUTH_TOKEN}
    volumes:
      - ./config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
